test: initial setup using k8s.

diff --git a/.github/workflows/build-test-release.yaml b/.github/workflows/build-test-release.yaml
--- a/.github/workflows/build-test-release.yaml
+++ b/.github/workflows/build-test-release.yaml
@@ -166,7 +166,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        splunk: ["8.2"]
+        splunk-version: ['8.2']
+        python-version: [3.7]
         browser: ["chrome", "firefox", "firefox_grid", "chrome_grid"]
         test_suit: [
           "test_splunk_ta_example_addon_logging",
@@ -180,6 +181,22 @@ jobs:
       - uses: actions/checkout@v2
         with:
           submodules: recursive
+      - name: Set up Python=${{ matrix.python-version }}
+        uses: actions/setup-python@v1
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Setup kubernetes cluster
+        id: kubernetes
+        run: |
+          ./k3s.sh
+          kubectl get no
+      - name: Setup Splunk-Operator at cluster-scope
+        run: |
+          wget -O splunk-operator.yaml https://github.com/splunk/splunk-operator/releases/download/1.0.5/splunk-operator-cluster.yaml
+          kubectl apply -f splunk-operator.yaml
+          sleep 30
+          kubectl get ns
+          kubectl get pods -A
       - uses: actions/download-artifact@v2
         with:
           name: package
@@ -196,69 +213,83 @@ jobs:
             pwd
             curl -s https://api.github.com/repos/splunk/splunk-add-on-for-ucc-example/releases/latest | grep "Splunk_TA.*.spl" | grep -v search_head | grep -v indexer | grep -v forwarder | cut -d : -f 2,3 | tr -d \" | wget -qi - || true
             ls
-            tar -xzf Splunk_TA*.spl
-            ls
-            rm Splunk_TA*.spl
-            ls
+            # tar -xzf Splunk_TA*.spl
+            # ls
+            # rm Splunk_TA*.spl
+            # ls
       - name: Setup for testing
         run: |
           echo "Setup for Testing..."
           pip install git+https://github.com/pixelb/crudini
           mkdir test-results
           cp -r tests/deps/splunk-add-on-for-ucc-example/output output
-      - name: Splunk Testing
+          ls -al
+          ls -al output
+      - name: Splunk Setup
         run: |
-          SPLUNK_VERSION=$(crudini --get tests/deps/build/addonfactory_test_matrix_splunk/splunk_matrix.conf "${{ matrix.splunk }}" VERSION)
-          export SPLUNK_VERSION
-          SPLUNK_APP_ID=$(crudini --get tests/deps/splunk-add-on-for-ucc-example/package/default/app.conf id name)
-          export SPLUNK_APP_ID
-          SPLUNK_APP_PACKAGE=tests/deps/splunk-add-on-for-ucc-example/output/$(ls tests/deps/splunk-add-on-for-ucc-example/output/)
-          export SPLUNK_APP_PACKAGE
+          echo "Splunk setup..."
+          export NAMESPACE_NAME=ta-ucc-example
+          export SPLUNK_ADDON="$(ls output)"
+          echo $SPLUNK_ADDON
+          export SPLUNK_VERSION=${{ matrix.splunk-version }}
+          echo $SPLUNK_VERSION
           export TEST_SET=tests/ui
           export TEST_BROWSER="${{ matrix.browser }}"
           export TEST_SUITE="-k ${{ matrix.test_suit }}"
           export SAUCE_USERNAME="${{ secrets.SAUCE_USERNAME }}"
           export SAUCE_PASSWORD="${{ secrets.SAUCE_PASSWORD }}"
-          export SAUCE_TUNNEL_ID="${{ secrets.SAUCE_TUNNEL_ID }}"
-          JOB_NAME="GithubActions::${GITHUB_REPOSITORY#splunk/}[${GITHUB_REF#refs/heads/}][${{ matrix.browser }}] #$(date +%s)"
-          export JOB_NAME
-          SAUCE_IDENTIFIER=$SAUCE_IDENTIFIER-$(cat /proc/sys/kernel/random/uuid)
-          export SAUCE_IDENTIFIER
-          echo "environment setup..."
-          echo "$SPLUNK_VERSION"
-          echo "$SPLUNK_APP_ID"
-          echo "$SPLUNK_APP_PACKAGE"
-          echo "$TEST_SET"
-          echo "$TEST_BROWSER"
-          echo "$TEST_SUITE"
-          echo "Testing..."
-          docker-compose -f docker-compose-ci.yml build
-          # Saucelab connection
-          docker-compose -f docker-compose-ci.yml up -d sauceconnect
+          export SAUCE_TUNNEL_ID="smartx-${GITHUB_REF#refs/heads/}:${{ matrix.browser }}:#$(date +%s)"
+          export SAUCE_IDENTIFIER=$SAUCE_TUNNEL_ID
+          # export SAUCE_TUNNEL_PARENT="ta-automation"
+          export JOB_NAME="GithubActions::${GITHUB_REPOSITORY#splunk/}[${GITHUB_REF#refs/heads/}][${{ matrix.browser }}] #$(date +%s)"
+          eval "echo \"$(cat ./namespace.yaml)\"" >> ./namespace_updated.yaml
+          eval "echo \"$(cat ./splunk_standalone.yaml)\"" >> ./splunk_standalone_updated.yaml
+          kubectl apply -f ./namespace_updated.yaml
+          kubectl run nginx -n $NAMESPACE_NAME --image=nginx --port=80 --expose
+          kubectl wait pod nginx --for=condition=ready --timeout=300s -n $NAMESPACE_NAME
+          kubectl cp ./output/$SPLUNK_ADDON nginx:/usr/share/nginx/html -n $NAMESPACE_NAME
+          echo "        - http://nginx//$SPLUNK_ADDON" >> ./splunk_standalone_updated.yaml
+          kubectl apply -f ./splunk_standalone_updated.yaml -n $NAMESPACE_NAME
+          until kubectl logs splunk-s1-standalone-0 -c splunk -n $NAMESPACE_NAME  | grep "Ansible playbook complete"; do sleep 1; done
+          kubectl port-forward svc/splunk-s1-standalone-service -n $NAMESPACE_NAME 8000:8000 8088:8088 8089:8089 9997:9997 &
+          # echo "Sauce connect proxy setup..."
+          echo "*********************************"
+          cat /etc/hosts
+
+          # echo "$SPLUNK_VERSION"
+          # echo "$SPLUNK_APP_ID"
+          # echo "$SPLUNK_APP_PACKAGE"
+          # echo "$TEST_SET"
+          # echo "$TEST_BROWSER"
+          # echo "$TEST_SUITE"
+          # echo "Testing..."
+          # docker-compose -f docker-compose-ci.yml build
+          # # Saucelab connection
+          # docker-compose -f docker-compose-ci.yml up -d sauceconnect
           
-          # Start selenium grid if needed.
-          if [[ "$TEST_BROWSER" == *"firefox_grid"* ]]; then docker-compose -f docker-compose-ci.yml up -d firefox-grid; fi
-          if [[ "$TEST_BROWSER" == *"chrome_grid"* ]]; then docker-compose -f docker-compose-ci.yml up -d chrome-grid; fi
-          # Start Splunk
-          docker-compose -f docker-compose-ci.yml up -d splunk
-          until docker-compose -f docker-compose-ci.yml logs splunk | grep "Ansible playbook complete" ; do sleep 1; done
-          # Normal Inspecting
-          docker-compose -f docker-compose-ci.yml logs sauceconnect
-          docker ps -a
-          # Run the tests
-          test_exit_code=0
-          docker-compose -f docker-compose-ci.yml up  --abort-on-container-exit test || test_exit_code=$?
-          # Collect Results
-          docker container create --name dummy \
-                              -v addon-factory-smartx-ui-test-library_results:/work/test-results \
-                              registry.access.redhat.com/ubi7/ubi
-          docker cp dummy:/work/test-results/test.xml test-results/ || true
-          docker cp dummy:/work/test-results/test.xml test-results/  || true
-          docker cp dummy:/work/assets test-results/assets  || true
-          docker cp dummy:/work/test-results/report.html test-results/report.html  || true
-          docker-compose -f docker-compose-ci.yml down || true
-          echo exit code "$test_exit_code"
-          exit "$test_exit_code"
+          # # Start selenium grid if needed.
+          # if [[ "$TEST_BROWSER" == *"firefox_grid"* ]]; then docker-compose -f docker-compose-ci.yml up -d firefox-grid; fi
+          # if [[ "$TEST_BROWSER" == *"chrome_grid"* ]]; then docker-compose -f docker-compose-ci.yml up -d chrome-grid; fi
+          # # Start Splunk
+          # docker-compose -f docker-compose-ci.yml up -d splunk
+          # until docker-compose -f docker-compose-ci.yml logs splunk | grep "Ansible playbook complete" ; do sleep 1; done
+          # # Normal Inspecting
+          # docker-compose -f docker-compose-ci.yml logs sauceconnect
+          # docker ps -a
+          # # Run the tests
+          # test_exit_code=0
+          # docker-compose -f docker-compose-ci.yml up  --abort-on-container-exit test || test_exit_code=$?
+          # # Collect Results
+          # docker container create --name dummy \
+          #                     -v addon-factory-smartx-ui-test-library_results:/work/test-results \
+          #                     registry.access.redhat.com/ubi7/ubi
+          # docker cp dummy:/work/test-results/test.xml test-results/ || true
+          # docker cp dummy:/work/test-results/test.xml test-results/  || true
+          # docker cp dummy:/work/assets test-results/assets  || true
+          # docker cp dummy:/work/test-results/report.html test-results/report.html  || true
+          # docker-compose -f docker-compose-ci.yml down || true
+          # echo exit code "$test_exit_code"
+          # exit "$test_exit_code"
       - uses: actions/upload-artifact@v2 
         if: always()
         with:
